### ISSUE TITLE
unifi-poller doesn't work on Kubernetes 1.22

### ISSUE THREAD

**Issue by samwho** [halkeye/helm-charts#1]
The `Ingress` resource has moved from `networking.k8s.io/v1beta1` to `networking.k8s.io/v1` so the chart sadly doesn't work on my updated cluster. Fix should be easy, though.

**Comment by halkeye** [comment]
hrm. I installed this and then never really did anything with it. I might just want to archive the project.

https://artifacthub.io/packages/helm/k8s-at-home/unifi-poller should be pretty well maintained, all their stuff usually is

That being said, if i can find the time i'll update it to my latest template - https://github.com/halkeye/helm-chart-starter

**Comment by samwho** [comment]
Ahhh I didn't realise k8s-at-home had a version. Thanks for the link!

I've been using your chart for the better part of a year. Thank you for creating it. 😄

**Comment by halkeye** [comment]
yea, most of my charts were created cause there was nothing out there at the time. I know the k8s-at-home team has taken a lot of them and converted them. Saves me a lot of effort.

I'll leave this open until I update the readme/archive it incase others have issues
